import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  modalBackground: {
    flex: 1,
     backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: '#151D34',
    borderRadius: 16,
    padding: 20,
    width: width * 0.9,
  },
  modalTitle: {
    fontSize: 20,
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: 'Raleway_700Bold',
  },
  inputLabel: {
    color: '#FFFFFF',
    marginTop: 12,
    marginBottom: 6,
    fontSize: 14,
    fontFamily: 'Raleway_700',
  },
  input: {
    borderWidth: 0.2,
    borderColor: '#FFFFFF',
    backgroundColor: '#172554',
    color: '#FFFFFF',
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    marginBottom: 10,
  },
  timeInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  iconBox: {
    width: 50,
    height: 50,
    backgroundColor: '#172554',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: '#FFFFFF',
  },
  timeInput: {
    flex: 1,
    color: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    backgroundColor: '#172554',
    borderRadius: 10,
    borderWidth: 0.2,
    borderColor: '#FFFFFF',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
  },
  cancelBtn: {
    flex: 0.6,
    backgroundColor: '#FBE6D8',
    borderColor: '#FF2304',
    borderWidth: 3,
    paddingVertical: 12,
    marginRight: 8,
    borderRadius: 30,
    alignItems: 'center',
  },
  cancelText: {
    color: '#FF2304',
    fontWeight: 'bold',
    fontSize: 16,
  },
  submitBtn: {
    flex: 1.3,
    backgroundColor: '#3352BA',
    paddingVertical: 12,
    marginLeft: 8,
    borderRadius: 30,
    alignItems: 'center',
  },
  submitText: {
    color: '#FFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
